[package]
name = "witchcraft-server-ete"
version.workspace = true
edition = "2021"
publish = false

[[bin]]
name = "witchcraft-server-ete"
test = false

[build-dependencies]
conjure-codegen = "5.0.0"

[dependencies]
async-trait = "0.1"
conjure-error = "5.0.0"
conjure-http = "5.0.0"
conjure-object = "5.0.0"
http = "1"
refreshable = "2"
tokio = "1"
witchcraft-server = { path = "../witchcraft-server" }

[dev-dependencies]
bytes = "1"
conjure-serde = "5.0.0"
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["tokio"] }
hyper = "1"
libc = "0.2"
rustls-pemfile = "2"
tempfile = "3.20.0"
tokio-rustls = { version = "0.26.2", default-features = false, features = ["ring", "tls12"] }

[target."cfg(windows)".dev-dependencies]
windows-sys = { version = "0.60.0", features = ["Win32_System_Console"] }
