[workspace.package]
version = "5.6.0"

[workspace]
resolver = "2"
members = [
    "render-conjure",
    "witchcraft-server",
    "witchcraft-server-config",
    "witchcraft-server-ete",
    "witchcraft-server-macros",
]

[patch.crates-io]
conjure-error = { git = "https://github.com/palantir/conjure-rust", branch = "param-stringify-flag" }
conjure-object = { git = "https://github.com/palantir/conjure-rust", branch = "param-stringify-flag" }
conjure-serde = { git = "https://github.com/palantir/conjure-rust", branch = "param-stringify-flag" }
conjure-http = { git = "https://github.com/palantir/conjure-rust", branch = "param-stringify-flag" }
conjure-macros = { git = "https://github.com/palantir/conjure-rust", branch = "param-stringify-flag" }
