[workspace.package]
version = "6.1.0"

[workspace]
resolver = "2"
members = [
    "witchcraft-server-macros",
    "witchcraft-server-config",
    "witchcraft-server",
    "witchcraft-server-ete",
    "render-conjure",
]

[patch.crates-io]
witchcraft-metrics = { git = "https://github.com/palantir/witchcraft-rust-logging", branch = "exemplars" }
